services:
  - docker

env:
  matrix:
    - DOCKER_USERNAME=dallasmakerspace

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export REPO=$(echo $TRAVIS_REPO_SLUG | tr -d '-' | tr 'A-Z' 'a-z')
  - docker image build -t $REPO:${TRAVIS_BRANCH:-"latest"} .

after_success:
  - docker image tag $REPO:${TRAVIS_BRANCH} $REPO:latest
  - docker push $REPO:latest
