services:
  - docker

env:
  matrix:
    - DOCKER_USERNAME=dallasmakerspace

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export REPO=$(echo $TRAVIS_REPO_SLUG |  tr 'A-Z' 'a-z' | tr -d '-' )
  - export TAG=${TRAVIS_COMMIT}
  - docker image build -t ${REPO}:${TAG} .

after_success:
  - docker image tag ${REPO}:${TRAVIS_BRANCH:-"latest"} ${REPO}:latest
  - docker push ${REPO}:latest
