services:
  - docker

env:
  matrix:
    - DOCKER_USERNAME=dallasmakerspace

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export REPO=$DOCKER_USERNAME
  - export TAG=${TRAVIS_COMMIT}
  docker manifest create
  - docker image build -t ${REPO}:linux-x86-64 .
  - docker image build --build-arg GOARCH=arm -t ${REPO}:linux-armv7 .

after_success:
  - docker manifest create ${REPO}:latest ${REPO}:linux-x86-64 ${REPO}:linux-armv7
  - docker manifest push ${REPO}:latest
