services:
  - docker

env:
  matrix:
    - DOCKER_USERNAME=dallasmakerspace

script:
  - docker image build -t $(echo $TRAVIS_REPO_SLUG | tr -d '-'):${TRAVIS_BRANCH:-"latest"} .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $REPO
