# Configuration file for ztDNS
suffix = "dms.local"
port = 53
interface = "zt0"

# Number of minutes to wait before updating the DNS database again (Default: 30)
DBRefresh = 15

# This section contains information related to your ZeroTier config
[ZT]
API = ""
URL = "https://my.zerotier.com/api"

# This section contains one or more ZeroTier networks with domain = "NetworkID"
[Networks]
dms.local = ''
